on: [push, pull_request]

jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'ubuntu-18.04']
        cc: [ 'gcc', 'clang' ]
    name: Compile via CMakeLists.txt on ${{ matrix.os }} using ${{ matrix.cc }}
    env:
      CFLAGS: '-Wextra -Werror'
      CXXFLAGS: '-Wextra -Werror'
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: make
      - run: make test
  make:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'ubuntu-18.04']
    name: Compile via Makefile on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: make -C src all VERBOSE=1
